version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
#    network_mode: "host"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: --bind_ip_all

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  couchdb:
    container_name: couchdb
    image: couchdb:latest
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: root
      COUCHDB_PASSWORD: password